apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "tenant.name" . }}-edit
  namespace: flux-system
subjects:
- kind: ServiceAccount
  name: {{ include "tenant.name" . }}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io