apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nginx
  namespace: flux-system
spec:
  dependsOn:
    - name: sources
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/nginx
  prune: true
  wait: true
  timeout: 5m
