apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  dependsOn:
    - name: nginx
    - name: rbac
    - name: sources
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./tenants/my-cluster/podinfo
  prune: true
  wait: true
  timeout: 5m
