apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: flux-system
spec:
  releaseName: podinfo
  targetNamespace: podinfo
  chart:
    spec:
      chart: ./charts/tenant
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 5m
  values:
    repo:
      url: ssh://git@github.com/mmontes11/flux-tenant-podinfo
      branch: master
      path: ./clusters/my-cluster
